name: Code Quality Main

# on:
#   pull_request:
#   push:
#     branches: [main]

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Find modified files
        if: env.commit_count > 1
        id: file_changes
        uses: trilom/file-changes-action@v1.2.4
        with:
          output: " "

      - name: List modified files
        if: env.commit_count > 1
        run: echo '${{ steps.file_changes.outputs.files}}'

      - name: Run pre-commits
        if: env.commit_count > 1
        uses: pre-commit/action@v3.0.0
